// lit/src/counter.ts
import { css, customElement, html, LitElement, property, PropertyValues } from "lit-element";
@customElement("wvn-counter")
class Counter extends LitElement
{
    static styles = [css`
    button
    {
        color:var(--wvn-button-color, red);
    }

    `];

    @property({type:Number})
    public count = 0;

    increment()
    {
        this.count++;
    }

    decrement()
    {
        this.count--;
    }

    update(changedProperties: PropertyValues)
    {
        super.update(changedProperties)
        if (changedProperties.has('count'))
        {
            this.dispatchEvent(new CustomEvent('counterChanged', {bubbles: true}));
        }
    }

    render()
    {
        console.info('render');
        return html`
<button part="decrement" @click=${this.decrement}>-</button>
<span part="count">${this.count}</span>
<button part="increment" @click=${this.increment}>+</button>
`;
    }
}

// svelte/src/Counter.svelte
<script lang="ts">
import { onMount } from "svelte";
import { get_current_component } from "svelte/internal";


    export let count = 0;

    export function increment()
    {
        count++;
    }

    export function decrement()
    {
        count--;
    }

    const host = get_current_component();
    $:host.dispatchEvent(new CustomEvent("counterChanged", {bubbles:true, detail:count}));
</script>

<style lang="scss">
    :host
    {
        color:blue;
    }

    :host([disabled])
    {
        color: grey;
    }

    button
    {
        color:green;
    }
</style>

<svelte:options tag="wvn-counter" />
    <button part="decrement" on:click={decrement}>-</button>
    <span part="count">{count}</span>
    <button part="increment"  on:click={increment}>+</button>
